root: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:svelte/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2020
  extraFileExtensions: ['.svelte']
env:
  browser: true
  es2017: true
  node: true
overrides:
  - files: ['*.svelte']
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
#rules:
#  indent:
#    - error
#    - 4
#  linebreak-style:
#    - error
#    - unix
#  quotes:
#    - error
#    - single
#  semi:
#    - error
#    - always
#  no-unused-vars:
#    - error
#    - varsIgnorePattern: '^_'
#      argsIgnorePattern: '^_'
#  no-trailing-spaces:
#    - error
