root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - import
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2020
  extraFileExtensions: ['.svelte']
settings:
  import/parsers:
    '@typescript-eslint/parser': ['.ts']
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: true
env:
  browser: true
  es2017: true
  node: true
overrides:
  - files: ['*.svelte']
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
rules:
  import/no-unresolved: off # Cannot handle $app correctly
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-import-type-side-effects': error
  'import/order':
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        orderImportKind: asc
        caseInsensitive: false
      groups:
        - builtin
        - external
        - internal
        - unknown # $app
        - parent
        - sibling
        - index
        - object
