services:
  db:
    image: mdillon/postgis:11
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "flugbuech"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: flugbuech
      POSTGRES_USER: flugbuech

  api:
    build: .
    restart: always
    ports:
      - "8000"
    links:
      - db
    volumes:
      - frontend-static:/static
    environment:
      ROCKET_PROFILE: release
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: 8000
      ROCKET_LOG_LEVEL: normal
      # IMPORTANT: Change the secret key below in production!
      # You can generate it with `openssl rand -base64 32`.
      ROCKET_SECRET_KEY: "2WMWUpOjLnmn39PIAifL4QXxGOsyyf1U17YTpOfoLJ4="
      DATABASE_URL: postgres://flugbuech@db/flugbuech
      ROCKET_DATABASES: '{flugbuech={url="postgres://flugbuech@db/flugbuech"}}'

  web:
    image: docker.io/nginx:1.29
    ports:
      - "8080:80"
    links:
      - "api:api"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-static:/flugbuech/static:ro

volumes:
  frontend-static:
