[global.limits]
forms = 3145728  # 3 MiB

[development]
static_files_dir = "static/"
secret_key = "eXqSA0wz+qLlg8umREPesnkBzNlhwaNcp34BttIWLes="

[development.databases]
flugbuech = { url = "postgres://localhost/flugbuech" }
