# Docs: https://rocket.rs/v0.5/guide/configuration/
#
# Rocket automatically sets the configuration profile to `debug` when compiled
# in debug mode and `release` when compiled in release mode.
#
# In addition to any profiles you declare, there are two meta-profiles,
# `default` and `global`, which can be used to provide values that apply to all
# profiles.  Values provided in a `default` profile are used as fall-back
# values when the selected profile doesn't contain a requested values, while
# values in the `global` profile supplant any values with the same name in any
# profile.

[global.limits]
form = "12 MiB"

[debug]
secret_key = "eXqSA0wz+qLlg8umREPesnkBzNlhwaNcp34BttIWLes="
cors_allow_origin = "*"

  [debug.databases.flugbuech]
  url = "postgres://flugbuech:flugbuech-dev-password@localhost/flugbuech"
  min_connections = 2
  max_connections = 8
  timeout = 5
