[global.limits]
forms = 3145728  # 3 MiB

[development]
static_files_dir = "static/"
secret_key = "eXqSA0wz+qLlg8umREPesnkBzNlhwaNcp34BttIWLes="

[development.databases]
flugbuech = { url = "postgres://localhost/flugbuech" }

[production]
keep_alive = 0  # Disabled until Rocket 0.5 (see https://matej.laitl.cz/bench-actix-rocket/)
