# Docs: https://rocket.rs/v0.5-rc/guide/configuration/
#
# Rocket automatically sets the configuration profile to `debug` when compiled
# in debug mode and `release` when compiled in release mode.
#
# In addition to any profiles you declare, there are two meta-profiles,
# `default` and `global`, which can be used to provide values that apply to all
# profiles.  Values provided in a `default` profile are used as fall-back
# values when the selected profile doesn't contain a requested values, while
# values in the `global` profile supplant any values with the same name in any
# profile.

[global.limits]
forms = "3 MiB"

[debug]
static_files_dir = "static"
secret_key = "eXqSA0wz+qLlg8umREPesnkBzNlhwaNcp34BttIWLes="

  [debug.databases.flugbuech]
  url = "postgres://localhost/flugbuech"
  timeout = 5
