# Generated by Django 2.1rc1 on 2018-07-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Skywalk Tequila 4', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='e.g. Advance or Skywalk', max_length=100)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, help_text='The flight number', null=True)),
                ('launch_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('max_altitude', models.IntegerField(blank=True, help_text='The max altitude reached during the flight', null=True)),
                ('distance', models.IntegerField(blank=True, help_text='The flight distance in kilometers', null=True)),
                ('comments', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('altitude', models.IntegerField(help_text='Elevation above sea level (AMSL) in meters')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='landing_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_landing', to='data.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='launch_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_launch', to='data.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
