# Generated by Django 2.1rc1 on 2018-07-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180719_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='landing_date',
        ),
        migrations.AddField(
            model_name='flight',
            name='video',
            field=models.URLField(blank=True, help_text='A link to a video of your flight', null=True),
        ),
    ]
