# Generated by Django 2.1 on 2018-08-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180719_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='distance',
            new_name='track_distance',
        ),
        migrations.AlterField(
            model_name='flight',
            name='track_distance',
            field=models.IntegerField(blank=True, help_text='The track distance in kilometers', null=True),
        ),
    ]
