# Generated by Django 2.1 on 2018-08-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180828_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='xcontest_distance',
            field=models.FloatField(blank=True, help_text='Flight distance in kilometers as calculated by XContest', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='xcontest_tracktype',
            field=models.CharField(blank=True, choices=[('free_flight', 'Free Flight'), ('flat_triangle', 'Flat Triangle'), ('fai_triangle', 'FAI Triangle')], help_text='XContest track type', max_length=64, null=True),
        ),
    ]
