# Generated by Django 2.1 on 2018-08-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_xcontest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='xcontest_url',
            field=models.URLField(blank=True, help_text='XContest flight URL', max_length=255, null=True),
        ),
    ]
