on: [push]

name: CI

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: mdillon/postgis:11
        env:
          POSTGRES_USER: flugbuech-user
          POSTGRES_PASSWORD: flugbuech-pass
          POSTGRES_DB: flugbuech
        ports:
          - 5432/tcp
        # Needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install -y libpq-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-09-03
          override: true
      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  lint:
    name: Run Clippy lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2019-09-03
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
